name: Artifact Action

on:
  workflow_dispatch:
    
jobs:
  create_file:
    runs-on: ubuntu-latest

    steps:
      - name: checkout code
        uses: actions/checkout@v4
      - name: create a file in linux
        run: echo "this is job1!" > file.txt

      - name: upload artifact
        uses: actions/upload-artifact@v4
        with: 
          name: job1-file
          path: file.txt

  Download_file:
    needs: create_file
    runs-on: ubuntu-latest
    steps:
      - name: Downloading
        uses: actions/download-artifact@v4
        with:
          name: job1-file

      - name: adding another line
        run: echo "this is job2!" >> file.txt

      - name: showing content
        run: cat file.txt

      - name: uploading again
        uses: actions/upload-artifact@v4
        with: 
          name: job2-file
          path: file.txt
      - name: commit and puh the file
        run: |
          git config user.name "github-actions"
          git config user.email "github-actions@github.com"
          cp job1.txt ./ 
          git add file.txt
          git commit -m "Updated file.txt"
          git push
