name: Artifact Action

on:
  workflow_dispatch:

jobs:
  create_file:
    runs-on: ubuntu-latest

    steps:
      - name: create a file in linux
        run: echo "this is job!" > file.txt

      - name: show the content
        run: cat file.txt
